name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH private key
      run: |
        echo "${{ secrets.AWS_PRIVATE_KEY }}" > devops-key.pem
        chmod 400 devops-key.pem

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no -i devops-key.pem ec2-user@3.83.68.73 "echo ✅ Connected to EC2!"
